-- ============================================================
-- SQL FINAL DEFINITIVO - EXECUTE APENAS ISTO
-- ============================================================

-- GARANTIR QUE ACIDENTES TEM TODAS AS COLUNAS
ALTER TABLE acidentes ADD COLUMN IF NOT EXISTS hora_ocorrencia TEXT;
ALTER TABLE acidentes ADD COLUMN IF NOT EXISTS local_ocorrencia TEXT;
ALTER TABLE acidentes ADD COLUMN IF NOT EXISTS causa_imediata TEXT;
ALTER TABLE acidentes ADD COLUMN IF NOT EXISTS medidas_corretivas TEXT;
ALTER TABLE acidentes ADD COLUMN IF NOT EXISTS dias_afastamento INTEGER;
ALTER TABLE acidentes ADD COLUMN IF NOT EXISTS cat BOOLEAN DEFAULT false;

-- GARANTIR QUE ENTREGAS TEM TODAS AS COLUNAS
ALTER TABLE entregas_epi ADD COLUMN IF NOT EXISTS devolvido BOOLEAN DEFAULT false;
ALTER TABLE entregas_epi ADD COLUMN IF NOT EXISTS data_devolucao TIMESTAMPTZ;
ALTER TABLE entregas_epi ADD COLUMN IF NOT EXISTS data_vencimento DATE;

-- DESABILITAR RLS EM TUDO
ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE funcionarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE epis DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacoes_estoque DISABLE ROW LEVEL SECURITY;
ALTER TABLE entregas_epi DISABLE ROW LEVEL SECURITY;
ALTER TABLE treinamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE funcionario_treinamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE acidentes DISABLE ROW LEVEL SECURITY;
ALTER TABLE documentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE assinaturas DISABLE ROW LEVEL SECURITY;
ALTER TABLE notificacoes DISABLE ROW LEVEL SECURITY;
